USE [master]
GO

CREATE DATABASE [SHOPPING]
 CONTAINMENT = NONE
 ON  PRIMARY ( 
NAME = N'SHOPPING', 
FILENAME = N'D:\Android App\LostShopping\Server\Database\SHOPPING.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SHOPPING_LOG', FILENAME = N'D:\Android App\LostShopping\Server\Database\SHOPPING_LOG.ldf' , SIZE = 2048KB , MAXSIZE = 1024MB , FILEGROWTH = 10%)
GO
USE SHOPPING
GO
CREATE TABLE CATEGORY 
(
	CAT_ID INT PRIMARY KEY IDENTITY(1,1),
	CAT_NAME NVARCHAR(50),
	CAT_DES NVARCHAR(100),
)

CREATE TABLE SUBCATEGORY
(
	SUBCAT_ID INT PRIMARY KEY IDENTITY(1,1),
	SUBCAT_NAME NVARCHAR(50),
	SUBCAT_DES NVARCHAR(100),
	SUBCAT_CAT_ID INT
)

CREATE TABLE SUPPIER
(
	SUP_ID INT PRIMARY KEY IDENTITY(1,1),
	SUP_COMPANY_NAME NVARCHAR(50),
	SUP_WEB_URL VARCHAR(30),
	SUP_ADDRESS NVARCHAR(50),
	SUP_TELEPHONE VARCHAR(20),
	SUP_EMAIL VARCHAR(30),
)

CREATE TABLE PRODUCT
(
	PRO_ID INT PRIMARY KEY IDENTITY(1,1),
	PRO_NAME NVARCHAR(50),
	PRO_DES NVARCHAR(100),
	PRO_LENGTH FLOAT,
	PRO_WIDTH FLOAT,
	PRO_DEPTH FLOAT,
	PRO_DIAMETER FLOAT,
	PRO_UNIT_WEIGHT FLOAT,
	PRO_COLOR VARCHAR(10),
	PRO_SUP_UNIT_PRICE FLOAT,
	PRO_SUP_QUANTITY FLOAT,
	PRO_SALE_UNIT_PRICE FLOAT,
	PRO_DISCOUNT_AVAILABLE FLOAT,
	PRO_DISCOUNT_PERCENT FLOAT,
	PRO_SUBCAT_ID INT,
	PRO_SUP_ID INT
)

CREATE TABLE ORDERS
(
	ORD_ID INT PRIMARY KEY IDENTITY(1,1),
	ORD_DATE DATE,
	ORD_PAID_STATUS BIT,
	ORD_TOTAL_AMOUNT FLOAT,
	ORD_SHIPPING_STATUS BIT,
	ORD_TOTLA_PRICE FLOAT,
	ORD_NOTE NVARCHAR(100),
	ORD_SER_ID INT,
	ORD_CUS_ID INT,
	ORD_BILL_ADDRESS NVARCHAR(50),
	ORD_BILL_CITY NVARCHAR(20),
	ORD_BILL_COUNTRY NVARCHAR(20),
	ORD_BILL_POSTCODE NVARCHAR(20)
)

CREATE TABLE ORDER_DETAIL
(
	OD_ID INT PRIMARY KEY IDENTITY(1,1),
	OD_ORD_ID INT,
	OD_PRO_ID INT,
	OD_PRO_NAME NVARCHAR(50),
	OD_PRO_UNIT_PRICE FLOAT,
	OD_PRO_AMOUNT FLOAT
)

CREATE TABLE DELIVERY_SERVICE
(
	SER_ID INT PRIMARY KEY IDENTITY(1,1),
	SER_NAME NVARCHAR(50),
	SER_DES NVARCHAR(100),
	SER_PARCEL_WEIGHT FLOAT,
	SER_MAXLENGTH FLOAT,
	SER_MAXWIDTH FLOAT,
	SER_MAXDEPTH FLOAT,
	SER_PRICE FLOAT,
	SER_ESTIMATE_DATE DATE
)

CREATE TABLE CUSTOMER
(
	CUS_ID INT PRIMARY KEY IDENTITY(1,1),
	CUS_ACCOUNT VARCHAR(50),
	CUS_PASS VARCHAR(50),
	CUS_FIRSTNAME NVARCHAR(20),
	CUS_LASTNAME NVARCHAR(20),
	CUS_ADDRESS NVARCHAR(50),
	CUS_CITY NVARCHAR(20),
	CUS_COUNTRY NVARCHAR(20),
	CUS_PHONE VARCHAR(20),
	CUS_EMAIL VARCHAR(30),
	CUS_REGISTRATION_DATE DATE
)

CREATE TABLE PAYMENT
(
	PAY_ID INT PRIMARY KEY IDENTITY (1,1),
	PAY_TYPE NVARCHAR(50)
)

CREATE TABLE IMAGES
(
	IMG_ID INT IDENTITY(1,1),
	IMG_ID_REF INT,
	IMG_PACTH NVARCHAR(100),
	PRIMARY KEY (IMG_ID,IMG_ID_REF)
)


-- ADD FOREIGN KEY
-- TABLE SUBCAT
ALTER TABLE SUBCATEGORY ADD CONSTRAINT FK_SUBCAT_CAT FOREIGN KEY (SUBCAT_CAT_ID) REFERENCES CATEGORY(CAT_ID)
-- TABLE PRODUCT
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRO_SUBCAT FOREIGN KEY (PRO_SUBCAT_ID) REFERENCES SUBCATEGORY(SUBCAT_ID)
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRO_SUP FOREIGN KEY (PRO_SUP_ID) REFERENCES SUPPIER(SUP_ID)
-- TABLE ORDERDETAIL
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ORDER_DETAIL_PRO FOREIGN KEY(OD_PRO_ID) REFERENCES PRODUCT(PRO_ID)
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ORDER_DETAIL_ORDERS FOREIGN KEY(OD_ORD_ID) REFERENCES ORDERS(ORD_ID)
-- TABLE ORDERS
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_DELIVERY_SERVICE FOREIGN KEY (ORD_SER_ID) REFERENCES DELIVERY_SERVICE(SER_ID)
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (ORD_CUS_ID) REFERENCES CUSTOMER(CUS_ID)

insert into CUSTOMER values(

USE SHOPPING
SELECT * FROM CATEGORY
SELECT * FROM PRODUCT
SELECT * FROM SUBCATEGORY
SELECT * FROM SUPPIER
SELECT * FROM ORDER_DETAIL
SELECT * FROM ORDERS
SELECT * FROM PAYMENT
SELECT * FROM DELIVERY_SERVICE
SELECT * FROM CUSTOMER
SELECT * FROM IMAGES