<?xml version="1.0" encoding="utf-8"?><Database Name="SHOPPING" Class="CategoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KYO\SQLEXPRESS;Initial Catalog=SHOPPING;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SHOPPINGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CATEGORY" Member="CATEGORies">
    <Type Name="CATEGORY">
      <Column Name="CAT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CAT_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CAT_DES" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>