<?xml version="1.0" encoding="utf-8"?><Database Name="SHOPPING" Class="CustomerManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KYO\SQLEXPRESS;Initial Catalog=SHOPPING;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SHOPPINGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="CUS_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CUS_ACCOUNT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUS_PASS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUS_FIRSTNAME" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CUS_LASTNAME" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CUS_ADDRESS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CUS_CITY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CUS_COUNTRY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CUS_PHONE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CUS_EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CUS_REGISTRATION_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>