#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostShoppingServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHOPPING")]
	public partial class CustomerManagerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    #endregion
		
		public CustomerManagerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SHOPPINGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerManagerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerManagerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerManagerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerManagerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CUS_ID;
		
		private string _CUS_ACCOUNT;
		
		private string _CUS_PASS;
		
		private string _CUS_FIRSTNAME;
		
		private string _CUS_LASTNAME;
		
		private string _CUS_ADDRESS;
		
		private string _CUS_CITY;
		
		private string _CUS_COUNTRY;
		
		private string _CUS_PHONE;
		
		private string _CUS_EMAIL;
		
		private System.Nullable<System.DateTime> _CUS_REGISTRATION_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUS_IDChanging(int value);
    partial void OnCUS_IDChanged();
    partial void OnCUS_ACCOUNTChanging(string value);
    partial void OnCUS_ACCOUNTChanged();
    partial void OnCUS_PASSChanging(string value);
    partial void OnCUS_PASSChanged();
    partial void OnCUS_FIRSTNAMEChanging(string value);
    partial void OnCUS_FIRSTNAMEChanged();
    partial void OnCUS_LASTNAMEChanging(string value);
    partial void OnCUS_LASTNAMEChanged();
    partial void OnCUS_ADDRESSChanging(string value);
    partial void OnCUS_ADDRESSChanged();
    partial void OnCUS_CITYChanging(string value);
    partial void OnCUS_CITYChanged();
    partial void OnCUS_COUNTRYChanging(string value);
    partial void OnCUS_COUNTRYChanged();
    partial void OnCUS_PHONEChanging(string value);
    partial void OnCUS_PHONEChanged();
    partial void OnCUS_EMAILChanging(string value);
    partial void OnCUS_EMAILChanged();
    partial void OnCUS_REGISTRATION_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCUS_REGISTRATION_DATEChanged();
    #endregion
		
		public CUSTOMER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CUS_ID
		{
			get
			{
				return this._CUS_ID;
			}
			set
			{
				if ((this._CUS_ID != value))
				{
					this.OnCUS_IDChanging(value);
					this.SendPropertyChanging();
					this._CUS_ID = value;
					this.SendPropertyChanged("CUS_ID");
					this.OnCUS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_ACCOUNT", DbType="VarChar(50)")]
		public string CUS_ACCOUNT
		{
			get
			{
				return this._CUS_ACCOUNT;
			}
			set
			{
				if ((this._CUS_ACCOUNT != value))
				{
					this.OnCUS_ACCOUNTChanging(value);
					this.SendPropertyChanging();
					this._CUS_ACCOUNT = value;
					this.SendPropertyChanged("CUS_ACCOUNT");
					this.OnCUS_ACCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_PASS", DbType="VarChar(50)")]
		public string CUS_PASS
		{
			get
			{
				return this._CUS_PASS;
			}
			set
			{
				if ((this._CUS_PASS != value))
				{
					this.OnCUS_PASSChanging(value);
					this.SendPropertyChanging();
					this._CUS_PASS = value;
					this.SendPropertyChanged("CUS_PASS");
					this.OnCUS_PASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_FIRSTNAME", DbType="NVarChar(20)")]
		public string CUS_FIRSTNAME
		{
			get
			{
				return this._CUS_FIRSTNAME;
			}
			set
			{
				if ((this._CUS_FIRSTNAME != value))
				{
					this.OnCUS_FIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._CUS_FIRSTNAME = value;
					this.SendPropertyChanged("CUS_FIRSTNAME");
					this.OnCUS_FIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_LASTNAME", DbType="NVarChar(20)")]
		public string CUS_LASTNAME
		{
			get
			{
				return this._CUS_LASTNAME;
			}
			set
			{
				if ((this._CUS_LASTNAME != value))
				{
					this.OnCUS_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._CUS_LASTNAME = value;
					this.SendPropertyChanged("CUS_LASTNAME");
					this.OnCUS_LASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_ADDRESS", DbType="NVarChar(50)")]
		public string CUS_ADDRESS
		{
			get
			{
				return this._CUS_ADDRESS;
			}
			set
			{
				if ((this._CUS_ADDRESS != value))
				{
					this.OnCUS_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._CUS_ADDRESS = value;
					this.SendPropertyChanged("CUS_ADDRESS");
					this.OnCUS_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_CITY", DbType="NVarChar(20)")]
		public string CUS_CITY
		{
			get
			{
				return this._CUS_CITY;
			}
			set
			{
				if ((this._CUS_CITY != value))
				{
					this.OnCUS_CITYChanging(value);
					this.SendPropertyChanging();
					this._CUS_CITY = value;
					this.SendPropertyChanged("CUS_CITY");
					this.OnCUS_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_COUNTRY", DbType="NVarChar(20)")]
		public string CUS_COUNTRY
		{
			get
			{
				return this._CUS_COUNTRY;
			}
			set
			{
				if ((this._CUS_COUNTRY != value))
				{
					this.OnCUS_COUNTRYChanging(value);
					this.SendPropertyChanging();
					this._CUS_COUNTRY = value;
					this.SendPropertyChanged("CUS_COUNTRY");
					this.OnCUS_COUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_PHONE", DbType="VarChar(20)")]
		public string CUS_PHONE
		{
			get
			{
				return this._CUS_PHONE;
			}
			set
			{
				if ((this._CUS_PHONE != value))
				{
					this.OnCUS_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CUS_PHONE = value;
					this.SendPropertyChanged("CUS_PHONE");
					this.OnCUS_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_EMAIL", DbType="VarChar(30)")]
		public string CUS_EMAIL
		{
			get
			{
				return this._CUS_EMAIL;
			}
			set
			{
				if ((this._CUS_EMAIL != value))
				{
					this.OnCUS_EMAILChanging(value);
					this.SendPropertyChanging();
					this._CUS_EMAIL = value;
					this.SendPropertyChanged("CUS_EMAIL");
					this.OnCUS_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_REGISTRATION_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CUS_REGISTRATION_DATE
		{
			get
			{
				return this._CUS_REGISTRATION_DATE;
			}
			set
			{
				if ((this._CUS_REGISTRATION_DATE != value))
				{
					this.OnCUS_REGISTRATION_DATEChanging(value);
					this.SendPropertyChanging();
					this._CUS_REGISTRATION_DATE = value;
					this.SendPropertyChanged("CUS_REGISTRATION_DATE");
					this.OnCUS_REGISTRATION_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
