#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostShoppingServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHOPPING")]
	public partial class ProductDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPRODUCT(PRODUCT instance);
    partial void UpdatePRODUCT(PRODUCT instance);
    partial void DeletePRODUCT(PRODUCT instance);
    #endregion
		
		public ProductDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SHOPPINGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PRODUCT> PRODUCTs
		{
			get
			{
				return this.GetTable<PRODUCT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCT")]
	public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PRO_ID;
		
		private string _PRO_NAME;
		
		private string _PRO_DES;
		
		private System.Nullable<double> _PRO_LENGTH;
		
		private System.Nullable<double> _PRO_WIDTH;
		
		private System.Nullable<double> _PRO_DEPTH;
		
		private System.Nullable<double> _PRO_DIAMETER;
		
		private System.Nullable<double> _PRO_UNIT_WEIGHT;
		
		private string _PRO_COLOR;
		
		private System.Nullable<double> _PRO_SUP_UNIT_PRICE;
		
		private System.Nullable<double> _PRO_SUP_QUANTITY;
		
		private System.Nullable<double> _PRO_SALE_UNIT_PRICE;
		
		private System.Nullable<double> _PRO_DISCOUNT_AVAILABLE;
		
		private System.Nullable<double> _PRO_DISCOUNT_PERCENT;
		
		private System.Nullable<int> _PRO_SUBCAT_ID;
		
		private System.Nullable<int> _PRO_SUP_ID;
		
		private string _PRO_IMAGE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRO_IDChanging(int value);
    partial void OnPRO_IDChanged();
    partial void OnPRO_NAMEChanging(string value);
    partial void OnPRO_NAMEChanged();
    partial void OnPRO_DESChanging(string value);
    partial void OnPRO_DESChanged();
    partial void OnPRO_LENGTHChanging(System.Nullable<double> value);
    partial void OnPRO_LENGTHChanged();
    partial void OnPRO_WIDTHChanging(System.Nullable<double> value);
    partial void OnPRO_WIDTHChanged();
    partial void OnPRO_DEPTHChanging(System.Nullable<double> value);
    partial void OnPRO_DEPTHChanged();
    partial void OnPRO_DIAMETERChanging(System.Nullable<double> value);
    partial void OnPRO_DIAMETERChanged();
    partial void OnPRO_UNIT_WEIGHTChanging(System.Nullable<double> value);
    partial void OnPRO_UNIT_WEIGHTChanged();
    partial void OnPRO_COLORChanging(string value);
    partial void OnPRO_COLORChanged();
    partial void OnPRO_SUP_UNIT_PRICEChanging(System.Nullable<double> value);
    partial void OnPRO_SUP_UNIT_PRICEChanged();
    partial void OnPRO_SUP_QUANTITYChanging(System.Nullable<double> value);
    partial void OnPRO_SUP_QUANTITYChanged();
    partial void OnPRO_SALE_UNIT_PRICEChanging(System.Nullable<double> value);
    partial void OnPRO_SALE_UNIT_PRICEChanged();
    partial void OnPRO_DISCOUNT_AVAILABLEChanging(System.Nullable<double> value);
    partial void OnPRO_DISCOUNT_AVAILABLEChanged();
    partial void OnPRO_DISCOUNT_PERCENTChanging(System.Nullable<double> value);
    partial void OnPRO_DISCOUNT_PERCENTChanged();
    partial void OnPRO_SUBCAT_IDChanging(System.Nullable<int> value);
    partial void OnPRO_SUBCAT_IDChanged();
    partial void OnPRO_SUP_IDChanging(System.Nullable<int> value);
    partial void OnPRO_SUP_IDChanged();
    partial void OnPRO_IMAGEChanging(string value);
    partial void OnPRO_IMAGEChanged();
    #endregion
		
		public PRODUCT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PRO_ID
		{
			get
			{
				return this._PRO_ID;
			}
			set
			{
				if ((this._PRO_ID != value))
				{
					this.OnPRO_IDChanging(value);
					this.SendPropertyChanging();
					this._PRO_ID = value;
					this.SendPropertyChanged("PRO_ID");
					this.OnPRO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_NAME", DbType="NVarChar(50)")]
		public string PRO_NAME
		{
			get
			{
				return this._PRO_NAME;
			}
			set
			{
				if ((this._PRO_NAME != value))
				{
					this.OnPRO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PRO_NAME = value;
					this.SendPropertyChanged("PRO_NAME");
					this.OnPRO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_DES", DbType="NVarChar(100)")]
		public string PRO_DES
		{
			get
			{
				return this._PRO_DES;
			}
			set
			{
				if ((this._PRO_DES != value))
				{
					this.OnPRO_DESChanging(value);
					this.SendPropertyChanging();
					this._PRO_DES = value;
					this.SendPropertyChanged("PRO_DES");
					this.OnPRO_DESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_LENGTH", DbType="Float")]
		public System.Nullable<double> PRO_LENGTH
		{
			get
			{
				return this._PRO_LENGTH;
			}
			set
			{
				if ((this._PRO_LENGTH != value))
				{
					this.OnPRO_LENGTHChanging(value);
					this.SendPropertyChanging();
					this._PRO_LENGTH = value;
					this.SendPropertyChanged("PRO_LENGTH");
					this.OnPRO_LENGTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_WIDTH", DbType="Float")]
		public System.Nullable<double> PRO_WIDTH
		{
			get
			{
				return this._PRO_WIDTH;
			}
			set
			{
				if ((this._PRO_WIDTH != value))
				{
					this.OnPRO_WIDTHChanging(value);
					this.SendPropertyChanging();
					this._PRO_WIDTH = value;
					this.SendPropertyChanged("PRO_WIDTH");
					this.OnPRO_WIDTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_DEPTH", DbType="Float")]
		public System.Nullable<double> PRO_DEPTH
		{
			get
			{
				return this._PRO_DEPTH;
			}
			set
			{
				if ((this._PRO_DEPTH != value))
				{
					this.OnPRO_DEPTHChanging(value);
					this.SendPropertyChanging();
					this._PRO_DEPTH = value;
					this.SendPropertyChanged("PRO_DEPTH");
					this.OnPRO_DEPTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_DIAMETER", DbType="Float")]
		public System.Nullable<double> PRO_DIAMETER
		{
			get
			{
				return this._PRO_DIAMETER;
			}
			set
			{
				if ((this._PRO_DIAMETER != value))
				{
					this.OnPRO_DIAMETERChanging(value);
					this.SendPropertyChanging();
					this._PRO_DIAMETER = value;
					this.SendPropertyChanged("PRO_DIAMETER");
					this.OnPRO_DIAMETERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_UNIT_WEIGHT", DbType="Float")]
		public System.Nullable<double> PRO_UNIT_WEIGHT
		{
			get
			{
				return this._PRO_UNIT_WEIGHT;
			}
			set
			{
				if ((this._PRO_UNIT_WEIGHT != value))
				{
					this.OnPRO_UNIT_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._PRO_UNIT_WEIGHT = value;
					this.SendPropertyChanged("PRO_UNIT_WEIGHT");
					this.OnPRO_UNIT_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_COLOR", DbType="VarChar(10)")]
		public string PRO_COLOR
		{
			get
			{
				return this._PRO_COLOR;
			}
			set
			{
				if ((this._PRO_COLOR != value))
				{
					this.OnPRO_COLORChanging(value);
					this.SendPropertyChanging();
					this._PRO_COLOR = value;
					this.SendPropertyChanged("PRO_COLOR");
					this.OnPRO_COLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_SUP_UNIT_PRICE", DbType="Float")]
		public System.Nullable<double> PRO_SUP_UNIT_PRICE
		{
			get
			{
				return this._PRO_SUP_UNIT_PRICE;
			}
			set
			{
				if ((this._PRO_SUP_UNIT_PRICE != value))
				{
					this.OnPRO_SUP_UNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._PRO_SUP_UNIT_PRICE = value;
					this.SendPropertyChanged("PRO_SUP_UNIT_PRICE");
					this.OnPRO_SUP_UNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_SUP_QUANTITY", DbType="Float")]
		public System.Nullable<double> PRO_SUP_QUANTITY
		{
			get
			{
				return this._PRO_SUP_QUANTITY;
			}
			set
			{
				if ((this._PRO_SUP_QUANTITY != value))
				{
					this.OnPRO_SUP_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._PRO_SUP_QUANTITY = value;
					this.SendPropertyChanged("PRO_SUP_QUANTITY");
					this.OnPRO_SUP_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_SALE_UNIT_PRICE", DbType="Float")]
		public System.Nullable<double> PRO_SALE_UNIT_PRICE
		{
			get
			{
				return this._PRO_SALE_UNIT_PRICE;
			}
			set
			{
				if ((this._PRO_SALE_UNIT_PRICE != value))
				{
					this.OnPRO_SALE_UNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._PRO_SALE_UNIT_PRICE = value;
					this.SendPropertyChanged("PRO_SALE_UNIT_PRICE");
					this.OnPRO_SALE_UNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_DISCOUNT_AVAILABLE", DbType="Float")]
		public System.Nullable<double> PRO_DISCOUNT_AVAILABLE
		{
			get
			{
				return this._PRO_DISCOUNT_AVAILABLE;
			}
			set
			{
				if ((this._PRO_DISCOUNT_AVAILABLE != value))
				{
					this.OnPRO_DISCOUNT_AVAILABLEChanging(value);
					this.SendPropertyChanging();
					this._PRO_DISCOUNT_AVAILABLE = value;
					this.SendPropertyChanged("PRO_DISCOUNT_AVAILABLE");
					this.OnPRO_DISCOUNT_AVAILABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_DISCOUNT_PERCENT", DbType="Float")]
		public System.Nullable<double> PRO_DISCOUNT_PERCENT
		{
			get
			{
				return this._PRO_DISCOUNT_PERCENT;
			}
			set
			{
				if ((this._PRO_DISCOUNT_PERCENT != value))
				{
					this.OnPRO_DISCOUNT_PERCENTChanging(value);
					this.SendPropertyChanging();
					this._PRO_DISCOUNT_PERCENT = value;
					this.SendPropertyChanged("PRO_DISCOUNT_PERCENT");
					this.OnPRO_DISCOUNT_PERCENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_SUBCAT_ID", DbType="Int")]
		public System.Nullable<int> PRO_SUBCAT_ID
		{
			get
			{
				return this._PRO_SUBCAT_ID;
			}
			set
			{
				if ((this._PRO_SUBCAT_ID != value))
				{
					this.OnPRO_SUBCAT_IDChanging(value);
					this.SendPropertyChanging();
					this._PRO_SUBCAT_ID = value;
					this.SendPropertyChanged("PRO_SUBCAT_ID");
					this.OnPRO_SUBCAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_SUP_ID", DbType="Int")]
		public System.Nullable<int> PRO_SUP_ID
		{
			get
			{
				return this._PRO_SUP_ID;
			}
			set
			{
				if ((this._PRO_SUP_ID != value))
				{
					this.OnPRO_SUP_IDChanging(value);
					this.SendPropertyChanging();
					this._PRO_SUP_ID = value;
					this.SendPropertyChanged("PRO_SUP_ID");
					this.OnPRO_SUP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_IMAGE", DbType="NVarChar(MAX)")]
		public string PRO_IMAGE
		{
			get
			{
				return this._PRO_IMAGE;
			}
			set
			{
				if ((this._PRO_IMAGE != value))
				{
					this.OnPRO_IMAGEChanging(value);
					this.SendPropertyChanging();
					this._PRO_IMAGE = value;
					this.SendPropertyChanged("PRO_IMAGE");
					this.OnPRO_IMAGEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
