<?xml version="1.0" encoding="utf-8"?><Database Name="SHOPPING" Class="ProductDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KYO\SQLEXPRESS;Initial Catalog=SHOPPING;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SHOPPINGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="PRO_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PRO_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRO_DES" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRO_LENGTH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_WIDTH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_DEPTH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_DIAMETER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_UNIT_WEIGHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_COLOR" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PRO_SUP_UNIT_PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_SUP_QUANTITY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_SALE_UNIT_PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_DISCOUNT_AVAILABLE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_DISCOUNT_PERCENT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRO_SUBCAT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRO_SUP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>